version: "3.7"

services:
  app:
    build: .
    container_name: healthcare_app
    depends_on:
      - db
      - redis
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/healthcare_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: healthcare_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    networks:
      - app_network



  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - 3308:3306
    networks:
      - app_network
    environment:
      MYSQL_DATABASE: healthcare_db
      MYSQL_USER: healthcare_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: anyrootpassword
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: healthcare_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  redisinsight:
    image: redis/redisinsight
    container_name: redis_insight
    restart: always
    depends_on:
      - redis
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data
    networks:
      - app_network


networks:
  app_network:

volumes:
  db_data:
  redis_data:
  redisinsight_data:
