spring.application.name=HealthCare
spring.datasource.url=jdbc:mysql://localhost:3307/healthcare_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=uxui2025

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
server.port=8081

spring.flyway.clean-disabled=false
spring.flyway.clean-on-validation-error=true

jwt.secret=maCleSecreteTresLongueDeAuMoins32CaracteresPourHS256
jwt.expiration=3600000


spring.security.oauth2.client.registration.google.client-id=YOUR_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_CLIENT_SECRET

spring.security.oauth2.client.registration.google.scope=openid,profile,email

spring.security.oauth2.client.provider.google.issuer-uri=https://accounts.google.com

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Pour voir Spring Security (utile pour comprendre pourquoi 403)
logging.level.org.springframework.security=DEBUG